; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AutoMeets"
#define MyAppVersion "1.0"
#define MyAppPublisher "KarMah"
#define MyAppExeName "AutoMeetsLauncher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{72EB8308-6616-4E7C-8FEC-1804D4968B8F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Installer
OutputBaseFilename=AutoMeets Setup (x86)
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\AutoMeetsLauncher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\AutoMeetsLauncher.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\AutoMeetsLauncher.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\AutoMeetsLauncher.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\AutoMeetsLauncher.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\ByteSize.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ygkar\Desktop\Projects\Visual Studio Projects\AutoMeetLauncherUpdater\Build\Apps\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: runascurrentuser nowait postinstall skipifsilent

